### ISSUE TITLE
Translate Readme to other languages

### ISSUE THREAD

**Issue by bumbummen99** [bumbummen99/leaflet.color-arrow#3]
In order to increase the use of the Readme and to reach a broader audience. In order to participate, please create a Translation and name it e.g. "Readme_en-US.md".

**Comment by eliamartani** [comment]
can I work on Readme_pt-BR ?

**Comment by jenlky** [comment]
Hi I would like to work on a Chinese translation. Will create a PR soon.

**Comment by prakharvk** [comment]
working on Hindi translation

**Comment by mariabp** [comment]
Working on Spanish translation!
